version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/ekart
permissions:
  - object: /home/ubuntu/ekart
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
      - location: scripts/clean_instance.sh
        timeout: 300
        runas: ubuntu
  AfterInstall:
      - location: scripts/softwareprop.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/python.sh
        timeout: 300
        runas: ubuntu
      # - location: scripts/gunicorn.sh
      #   timeout: 300
      #   runas: ubuntu
      # - location: scripts/nginx.sh
      #   timeout: 300
      #   runas: ubuntu
  ApplicationStop:
      - location: scripts/stop_app.sh
        timeout: 300
        runas: ubuntu
  ApplicationStart:
      - location: scripts/start_app.sh
        timeout: 300
        runas: ubuntu
